version: "3.8"
services:
  devcontainer:
    build: 
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports: 
      - "80:80"
    depends_on: 
      - backend

  backend:
    build: 
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports: 
      - "5001:5001"
    depends_on:
      - db
    environment:
      DB_URL: postgresql://postgres:mysecretpassword@db:5432/postgres
    
  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../backend/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: