version: "3.8"
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: Dockerfile
    network_mode: service:db
    
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: