name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          docker-compose -f .devcontainer/docker-compose.yml build
#          docker-compose -f .devcontainer/docker-compose.yml run devcontainer python -m pytest
